version: 0.2

env:
  variables:
    IMAGE_NAME: docx-to-image-lambda

phases:
  pre_build:
    commands:
      - ECR_URI=<your_account_id>.dkr.ecr.eu-central-1.amazonaws.com
      - IMAGE_URI=$ECR_URI/$IMAGE_NAME
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin $ECR_URI
  build:
    commands:
      - echo Building production Docker image...
      - docker build -t $IMAGE_URI:latest -f Dockerfile.prod .
  post_build:
    commands:
      - docker push $IMAGE_URI:latest
      - aws lambda update-function-code \
          --function-name docx-to-image \
          --image-uri $IMAGE_URI:latest
