version: "3.8"

services:
  lambda:
    build:
      context: .
      target: tester
    ports:
      - "9000:8080"
    volumes:
      - ~/.aws:/root/.aws:ro
    environment:
      AWS_PROFILE: default
      AWS_REGION: eu-central-1

  packager:
    build:
      context: .
      target: packager
    volumes:
      - ./output:/opt/output
    command: ["/opt/build/package.sh"]