FROM --platform=linux/x86_64 public.ecr.aws/lambda/python:3.13

# Set the default working directory Lambda expects
WORKDIR /var/task

# Copy function code
COPY lambda_function.py .
COPY requirements.txt .

# Install dependencies into /var/task
RUN pip install --no-cache-dir -r requirements.txt -t .

# Default Lambda entrypoint
CMD ["lambda_function.lambda_handler"]